### ISSUE TITLE
Weapon change -  Shouldn't be taken

### ISSUE THREAD

**Issue by SebastienTolron** [jfnaud/Guild-Wars-2-Gold-per-hour#11]
Hey ! 

First of all thanks for the great job.

Everytime I swap my weapon, the tool considers that I lost it. Or that I loot it.

Si i get like -3000g in my result which are not correct.

I havent used it for a while because of it , maybe it has already been fixed.

Regards

**Comment by jfnaud** [comment]
Sorry for the delay, somehow I still don't receive notifications from github...

If I remember correctly, there are two different API endpoints: one for your equipped items, and one for your inventory. It might be the case that they don't update as frequently, explaining why it appears as "lost" for a time. Maybe if you wait for a refresh or two it would no longer appear as lost...

**Comment by jackpoz** [comment]
This is still an issue, every time I swap equipment template it considers all affected weapons as found/lost

**Comment by jackpoz** [comment]
This is my hackfix to consider Legendary items worth 0 gold to avoid issues when swapping weapons. Ascended items are already worth 0 gold so it pretty much fixes most of the cases

![image](https://user-images.githubusercontent.com/1153754/190927290-6ff8ccd0-30db-4f91-b800-d17c57b7ba1e.png)

https://github.com/jackpoz/Guild-Wars-2-Gold-per-hour/commit/acbacb2c36d84bb3134a49ce465367e1ba5c61d7

**Comment by jfnaud** [comment]
Thank you, I'll look into it this week! A better solution might be to check if the item is account bound or soul bound, but I'm not sure if we have that information. Also there is maybe another API endpoint for items in gear templates, it didn't exist at the time.

I didn't look at the code in years, I wasn't even aware that the tool was still used :)

**Comment by jackpoz** [comment]
it's a really good tool, I often start it up, play and have fun and at the end check if I ended up even getting some gold out of it 😃 thanks for all the effort you put into building it 🚀

**Comment by jfnaud** [comment]
After looking into it, I think I understand what is happening with legendary items and equipment templates. I also think I have a solution - though not perfect.

Previously, the app would check the currently equipped items only - it was built before equipment templates existed. Now that you can have multiple templates, a single item can be equipped in multiple templates. Also, when you switch to a new template, since the app only scans for currently equipped items, some may appear as lost or gained. As you noted, this can have a dramatic effect when legendary items are involved, even though the items are not lost or gained.

For the legendary items themselves, the fix was quite easy: I can use the "new" /account/legendaryarmory API endpoint to fetch all the legendaries that are bound to the account. When scanning the equipment, I simply ignore these legendaries, since they will already be fetched from the armory. Acquiring or losing non-bound legendaries should still be listed.

However I found it was still confusing that switching your gear template makes non-legendary items appear as gained/lost. There is a "new" endpoint to scan all equipment templates instead, but this leads to another problem. Let's say you loot a new sword from a monster, then equip that sword in 5 different equipment templates, the app would show 5 new swords were gained.

Since I was not sure what was the best solution (scanning the currently equipped items only vs all equipment templates), I added a new option in the Settings popup to specify which method you prefer. The default is scanning only the equipped items - just like before.

Let me know if you find any bug with those changes. Thank you!

**Comment by jackpoz** [comment]
The new version is having some issues:
![image](https://user-images.githubusercontent.com/1153754/191608071-de58ab97-9531-47bb-8064-e0ef62b4389e.png)

Causing this
![image](https://user-images.githubusercontent.com/1153754/191607947-ed9783f3-7b26-4f61-94c0-91fe2e966e27.png)

And never showing any updated item.

This happens on first page load and at every later API refresh.

Every other API call works fine:
![image](https://user-images.githubusercontent.com/1153754/191608684-81c9be14-dfeb-4fdf-aab7-82c099641b42.png)

**Comment by jackpoz** [comment]
According to https://wiki.guildwars2.com/wiki/API:2/account/legendaryarmory , the legendaryarmory api requires "unlocks" as API permission that was not required before. After creating a new key it's working fine, but maybe it's good to catch that exception and still have the application work so existing users will think "ah it's broken".

Maybe a warning message like "please include unlock as API permission to handle legendaries" when it returns HTTP 403 :)

Thanks a lot for the fixes btw :)

**Comment by jfnaud** [comment]
Ah I see, thank you!

I will fix this later tonight.

**Comment by jfnaud** [comment]
I added a simple check if the response is empty - a bit ugly but it should do the job.

Apparently the server does not send the "access-control-allow-origin" header when a permission is missing, which makes the browser completely block the request before the code can check the HTTP code...

**Comment by jackpoz** [comment]
Strange behavior with the new version:
![image](https://user-images.githubusercontent.com/1153754/192073620-7f581293-ff47-4eb3-996e-caf7ce89a2e1.png)

I have legendary armor with different stats in different equipment templates, it showed them as lost items.

These are my settings (I think they are the default ones):
![image](https://user-images.githubusercontent.com/1153754/192073657-f45fb6be-113a-4089-b912-5d441aa50f11.png)

No big deal though as I am very happy with the latest changes ignoring the value of legendary weapons 👍 🚀 🥳

**Comment by jfnaud** [comment]
I think it's because the app is only scanning for your currently equipped items. If you scan all your equipment templates, you should no longer see the lengedaries in the lost/gained sections!

**Comment by jackpoz** [comment]
Thanks, I'll check that setting out
